appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XSfxMHprgETMnqcpq1Ee9kJWKIUtLEgXAo5w02hzalYrirejQ8kSHS+RIxSUnmSOrWUz57WYPwl3Poq43pitXLr5p/auLeZm6G1DdaOYy2m3aGAhIi7UPuEg+rGHrddh5zKSNKQG4Q0JE4I8H5ioPHCj1fKLXDLP4CKs1BC654ynIR87DQoyy4gpXuGhz5qOSKuTboqYK5wTjiRhlzgG/2UQrERyqF1DP6u2tV8e9yBVqwSdrCHmlEpr4tUbYphbP+jluO+Z/K5KEBQmMWESaphch6/qy3KcBrlAnrKwHeFnL5e35n4Go4nWN6Sgj/j6fpS2/KBjbft1+OSqGXe1ffFZU8VeNtsOnRf761tmRTwBQWFn3VceU90FR8AHyhpx0Uwy+Ojt2Gjw/3StOKoV4IhL9f9T21xnSu0ozDaQCeo0h2CoOwzdkS3qbRwZB+X3t7pkeuNp81d/ikERyRyQDpWrtssFz9GU/HVcUEdwJE1/04yzcO45CZr4km5vYFMjr2HdjoZt/KPOZR2XCUBdq9gwUWv+BCcIB8r96isNsn0U7o+K/1gZ75siGXtFH4+kf+hGNLghY2xa+ptA8BRzncC8UZDhIp6vFRPWDtvxvaDBvRIfC1cl1S+N1suwzQXmMrT+HFhtKY1Ykgr7+P332ysvnNo57Q4ORDk8uF6yCx0=}
bot:
  automerge: true
