travis:
  secure:
    BINSTAR_TOKEN: Gd06brIr22d299HefAPHVry2yQashfrviWAVdHnIN0N2wNZ5UKI/ZeqaMewRXdni1iGX6jBptvQ70fD/qL8FbfEx0rDJ9EsREPRaR2OhTKBn7IgVAuW3GkAOg6zqOsn8TtVU8aE0aGrLAdkZhyc5hQr5Il7r7g5yX0LCMESPV/EE4AxHbkcfDINisaqyT1KP6A+fR2TsJjbGBeIV6kqcPk1zEtTtXU7HlfSNkXK3NFsdwZm54rjdPa9EspziTXJFbVCwNnVVs2iNT6jR0RmFNDaIYv2gnKkY4+OvUbAUBgLVTHvAOxzrpJKtJqrgfBTKKZhZkD93DIgk4ctLJBQAriqJxZciRef+5J8vmVgnBiWkyPIqx0kAgQkvhzQSrc1U3UsmxbdBRCvj0h4fhnmNxMQAMpP3n6djVWD71ZVcdl0CnC+gZ6AI6jNHXJCggwYOSgxiU5IFSKzGJrpGlOFIOm3yRoqNp9qSVGhAUOGwN1W3qvfjZBCXw7Ks00wCRlwvPIcfMvAo6KXqZvkrekR7HGi8BMB8jObIHi606MFw8csfn1Fn/fe6Rie3/Ufmo/O7dSUSLAhJkZ/2LipUApceK2rM9WjNzcCro1QtXdeIwVWQfFQhSOt9M+JjArpStLBb0MOaabINVn9HSrdBt1kx9G/7eTDcB5LzM02dkH2PeVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
